/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imageSorter;

import imageSorter.CustomActionsDialog.CustomAction;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.awt.Point;
import java.awt.Rectangle;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.TextStyle;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.TreeMap;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import static javax.swing.KeyStroke.getKeyStroke;
import javax.swing.Timer;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import javax.swing.event.MouseInputAdapter;

/**
 *
 * @author dougthompson
 */
public class ImageSorterFrame extends javax.swing.JFrame {

    /**
     * Creates new form ImageSorterFrame
     */
    public ImageSorterFrame() {
        initComponents();
        initMyComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jButtonBrowseMoveTo = new javax.swing.JButton();
        jButtonBrowseSource = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBoxAutoCreateDirs = new javax.swing.JCheckBox();
        jComboBoxSource = new javax.swing.JComboBox<>();
        jButtonBrowseDeleteTo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxMoveToDestination = new javax.swing.JComboBox<>();
        jComboBoxDeleteToDestination = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jCheckBoxCopyOnly = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelNext = new javax.swing.JLabel();
        jLabelPrevious = new javax.swing.JLabel();
        jSliderBrowsePictures = new javax.swing.JSlider();
        imageLabel = new imageSorter.ImageLabel();
        jPanel4 = new javax.swing.JPanel();
        jTextFieldFilename = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabelMonth = new javax.swing.JLabel();
        jLabelFilenameExtension = new javax.swing.JLabel();
        jLabelYear = new javax.swing.JLabel();
        jLabelXofY = new javax.swing.JLabel();
        jButtonMove = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelDestination = new javax.swing.JLabel();
        jButtonBrowseDir = new javax.swing.JButton();
        jComboBoxDirName = new javax.swing.JComboBox<>();
        jLabelStatus = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanelCustomActions = new javax.swing.JPanel();
        jButtonCustomizeActions = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemUndo = new javax.swing.JMenuItem();
        jMenuItemRenameFile = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSplitPane1MouseClicked(evt);
            }
        });

        jButtonBrowseMoveTo.setText("...");
        jButtonBrowseMoveTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseMoveToActionPerformed(evt);
            }
        });

        jButtonBrowseSource.setText("...");
        jButtonBrowseSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBrowseSourceActionPerformed(evt);
            }
        });

        jLabel2.setText("'Move To' Directory:");
        jLabel2.setToolTipText("When moving or copying, the location the pictures will be moved to");

        jCheckBoxAutoCreateDirs.setText("Auto create and organize by year\\month");
        jCheckBoxAutoCreateDirs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxAutoCreateDirsActionPerformed(evt);
            }
        });

        jComboBoxSource.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\\Volumes\\External Hard Drive\\Brandon\\MyPictures\\", "Item 2", "Item 3", "Item 4" }));
            jComboBoxSource.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jComboBoxSourceActionPerformed(evt);
                }
            });

            jButtonBrowseDeleteTo.setText("...");
            jButtonBrowseDeleteTo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButtonBrowseDeleteToActionPerformed(evt);
                }
            });

            jLabel1.setText("Source Directory:");
            jLabel1.setToolTipText("Location of the pictures you want to sort, move, or delete");

            jComboBoxMoveToDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\\Volumes\\External Hard Drive\\Pictures\\Brandon\\Sorted\\", "Item 2", "Item 3", "Item 4" }));
                jComboBoxMoveToDestination.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        jComboBoxMoveToDestinationActionPerformed(evt);
                    }
                });

                jComboBoxDeleteToDestination.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "\\Volumes\\External Hard Drive\\Brandon\\Deleted\\", "Item 2", "Item 3", "Item 4" }));
                    jComboBoxDeleteToDestination.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jComboBoxDeleteToDestinationActionPerformed(evt);
                        }
                    });

                    jLabel3.setText("'Delete' Directory:");
                    jLabel3.setToolTipText("When an image is 'deleted', it is moved to this location");

                    jCheckBoxCopyOnly.setText("Copy only - keep source file");
                    jCheckBoxCopyOnly.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jCheckBoxCopyOnlyActionPerformed(evt);
                        }
                    });

                    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                    jPanel2.setLayout(jPanel2Layout);
                    jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxDeleteToDestination, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonBrowseDeleteTo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBoxSource, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonBrowseSource, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jCheckBoxAutoCreateDirs)
                                            .addGap(18, 18, 18)
                                            .addComponent(jCheckBoxCopyOnly)
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(jComboBoxMoveToDestination, 0, 609, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonBrowseMoveTo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addContainerGap())
                    );
                    jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jComboBoxSource, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonBrowseSource))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jComboBoxMoveToDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonBrowseMoveTo))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBoxAutoCreateDirs)
                                .addComponent(jCheckBoxCopyOnly))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jComboBoxDeleteToDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButtonBrowseDeleteTo))
                            .addContainerGap())
                    );

                    jSplitPane1.setLeftComponent(jPanel2);

                    jLabelNext.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                    jLabelNext.setText(">");
                    jLabelNext.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            jLabelNextMouseClicked(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                            jLabelNextMouseExited(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                            jLabelNextMouseEntered(evt);
                        }
                    });

                    jLabelPrevious.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                    jLabelPrevious.setText("<");
                    jLabelPrevious.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                            jLabelPreviousMouseClicked(evt);
                        }
                        public void mouseExited(java.awt.event.MouseEvent evt) {
                            jLabelPreviousMouseExited(evt);
                        }
                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                            jLabelPreviousMouseEntered(evt);
                        }
                    });

                    jSliderBrowsePictures.setToolTipText("");
                    jSliderBrowsePictures.setValue(0);

                    imageLabel.setPreferredSize(new java.awt.Dimension(200, 200));

                    javax.swing.GroupLayout imageLabelLayout = new javax.swing.GroupLayout(imageLabel);
                    imageLabel.setLayout(imageLabelLayout);
                    imageLabelLayout.setHorizontalGroup(
                        imageLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                    );
                    imageLabelLayout.setVerticalGroup(
                        imageLabelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                    );

                    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jLabelPrevious)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jSliderBrowsePictures, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelNext)
                            .addGap(18, 18, 18))
                        .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 629, Short.MAX_VALUE)
                    );
                    jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(imageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jSliderBrowsePictures, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelNext)
                                .addComponent(jLabelPrevious))
                            .addContainerGap())
                    );

                    jTextFieldFilename.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
                    jTextFieldFilename.setText("DSC00123");
                    jTextFieldFilename.addFocusListener(new java.awt.event.FocusAdapter() {
                        public void focusGained(java.awt.event.FocusEvent evt) {
                            jTextFieldFilenameFocusGained(evt);
                        }
                        public void focusLost(java.awt.event.FocusEvent evt) {
                            jTextFieldFilenameFocusLost(evt);
                        }
                    });
                    jTextFieldFilename.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                            jTextFieldFilenameKeyTyped(evt);
                        }
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                            jTextFieldFilenameKeyReleased(evt);
                        }
                    });

                    jLabel10.setText("Filename:");

                    jLabelMonth.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                    jLabelMonth.setText("November");

                    jLabelFilenameExtension.setText(".jpg");

                    jLabelYear.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
                    jLabelYear.setText("2016");

                    jLabelXofY.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                    jLabelXofY.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabelXofY.setText("Image 3 of 40");

                    jButtonMove.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                    jButtonMove.setForeground(new java.awt.Color(0, 102, 0));
                    jButtonMove.setText("Move");
                    jButtonMove.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButtonMoveActionPerformed(evt);
                        }
                    });

                    jButtonDelete.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
                    jButtonDelete.setForeground(new java.awt.Color(255, 0, 51));
                    jButtonDelete.setText("Delete");
                    jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButtonDeleteActionPerformed(evt);
                        }
                    });

                    jLabel4.setText("Dir Name:");

                    jLabel5.setText("Destination:");

                    jLabelDestination.setText("jLabel6");

                    jButtonBrowseDir.setText("...");
                    jButtonBrowseDir.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButtonBrowseDirActionPerformed(evt);
                        }
                    });

                    jComboBoxDirName.setEditable(true);
                    jComboBoxDirName.addItemListener(new java.awt.event.ItemListener() {
                        public void itemStateChanged(java.awt.event.ItemEvent evt) {
                            jComboBoxDirNameItemStateChanged(evt);
                        }
                    });
                    jComboBoxDirName.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jComboBoxDirNameActionPerformed(evt);
                        }
                    });
                    jComboBoxDirName.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyTyped(java.awt.event.KeyEvent evt) {
                            jComboBoxDirNameKeyTyped(evt);
                        }
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                            jComboBoxDirNameKeyReleased(evt);
                        }
                    });

                    jLabelStatus.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
                    jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                    jLabelStatus.setText("jLabel6");

                    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                    jPanel4.setLayout(jPanel4Layout);
                    jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabelXofY, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                                    .addGap(20, 20, 20)
                                    .addComponent(jButtonMove)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButtonDelete))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelDestination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jComboBoxDirName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jButtonBrowseDir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextFieldFilename)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabelFilenameExtension)))
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabelYear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabelMonth)))
                            .addContainerGap())
                    );
                    jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jButtonMove)
                                .addComponent(jLabelXofY)
                                .addComponent(jButtonDelete)
                                .addComponent(jLabelStatus))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel10)
                                .addComponent(jTextFieldFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelFilenameExtension)
                                .addComponent(jLabelYear)
                                .addComponent(jLabelMonth)
                                .addComponent(jLabel4)
                                .addComponent(jButtonBrowseDir)
                                .addComponent(jComboBoxDirName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jLabelDestination))
                            .addContainerGap())
                    );

                    jPanelCustomActions.setAutoscrolls(true);
                    jPanelCustomActions.setLayout(new java.awt.GridBagLayout());

                    jButtonCustomizeActions.setBackground(new java.awt.Color(49, 138, 37));
                    jButtonCustomizeActions.setForeground(new java.awt.Color(255, 255, 255));
                    jButtonCustomizeActions.setText("Modify Actions");
                    jButtonCustomizeActions.setToolTipText("<html>Create and edit additional places<br/>to copy the image to</html>");
                    jButtonCustomizeActions.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jButtonCustomizeActionsActionPerformed(evt);
                        }
                    });
                    gridBagConstraints = new java.awt.GridBagConstraints();
                    gridBagConstraints.gridx = 0;
                    gridBagConstraints.gridy = 0;
                    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
                    gridBagConstraints.insets = new java.awt.Insets(6, 6, 312, 6);
                    jPanelCustomActions.add(jButtonCustomizeActions, gridBagConstraints);

                    jScrollPane1.setViewportView(jPanelCustomActions);

                    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                    jPanel3.setLayout(jPanel3Layout);
                    jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap())
                    );
                    jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                    );

                    jSplitPane1.setRightComponent(jPanel3);

                    jMenu1.setText("File");

                    jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
                    jMenuItemExit.setText("Exit");
                    jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jMenuItemExitActionPerformed(evt);
                        }
                    });
                    jMenu1.add(jMenuItemExit);

                    jMenuBar1.add(jMenu1);

                    jMenu2.setText("Edit");

                    jMenuItemUndo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
                    jMenuItemUndo.setText("Undo");
                    jMenuItemUndo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jMenuItemUndoActionPerformed(evt);
                        }
                    });
                    jMenu2.add(jMenuItemUndo);

                    jMenuItemRenameFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
                    jMenuItemRenameFile.setText("Rename File");
                    jMenuItemRenameFile.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                            jMenuItemRenameFileActionPerformed(evt);
                        }
                    });
                    jMenu2.add(jMenuItemRenameFile);

                    jMenuBar1.add(jMenu2);

                    setJMenuBar(jMenuBar1);

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1)
                    );
                    layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSplitPane1)
                    );

                    pack();
                }// </editor-fold>//GEN-END:initComponents

    private void jButtonBrowseSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseSourceActionPerformed
        selectSource();
    }//GEN-LAST:event_jButtonBrowseSourceActionPerformed

    private void jButtonBrowseMoveToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseMoveToActionPerformed
        selectMoveTo();
    }//GEN-LAST:event_jButtonBrowseMoveToActionPerformed

    private void jButtonBrowseDeleteToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseDeleteToActionPerformed
        selectDeleteTo();
    }//GEN-LAST:event_jButtonBrowseDeleteToActionPerformed

    private void jComboBoxSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSourceActionPerformed
        if (!initializing) {
            savePaths(selectSourceList, sourceFileName, jComboBoxSource);
            getSourceFiles(false);
        }

    }//GEN-LAST:event_jComboBoxSourceActionPerformed

    private void jComboBoxMoveToDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMoveToDestinationActionPerformed
        if (!initializing) {
            savePaths(moveToList, moveToFileName, jComboBoxMoveToDestination);
            updateDestinationLabel();
        }
    }//GEN-LAST:event_jComboBoxMoveToDestinationActionPerformed

    private void jComboBoxDeleteToDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDeleteToDestinationActionPerformed
        if (!initializing) {
            savePaths(deleteToList, deleteToFileName, jComboBoxDeleteToDestination);
            updateDestinationLabel();
        }
    }//GEN-LAST:event_jComboBoxDeleteToDestinationActionPerformed

    private void jCheckBoxAutoCreateDirsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxAutoCreateDirsActionPerformed
        updateDestinationLabel();
        saveSettings();
    }//GEN-LAST:event_jCheckBoxAutoCreateDirsActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        //this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        moveImage(getDestination((String) jComboBoxDeleteToDestination.getSelectedItem(), FileMoveType.DELETE), FileMoveType.DELETE);
        //this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMoveActionPerformed
        //this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        if (jCheckBoxCopyOnly.isSelected()) {
            moveImage(getDestination((String) jComboBoxMoveToDestination.getSelectedItem(), FileMoveType.COPY), FileMoveType.COPY);
        } else {
            moveImage(getDestination((String) jComboBoxMoveToDestination.getSelectedItem(), FileMoveType.MOVE), FileMoveType.MOVE);
        }
        //this.setCursor(Cursor.getDefaultCursor());
    }//GEN-LAST:event_jButtonMoveActionPerformed

    private void jLabelPreviousMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPreviousMouseClicked
        getPreviousImage();
    }//GEN-LAST:event_jLabelPreviousMouseClicked

    private void jLabelNextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNextMouseClicked
        getNextImage();
    }//GEN-LAST:event_jLabelNextMouseClicked

    private void jMenuItemUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUndoActionPerformed
        undoLastAction();
    }//GEN-LAST:event_jMenuItemUndoActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemRenameFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemRenameFileActionPerformed
        selectFileNameField();
    }//GEN-LAST:event_jMenuItemRenameFileActionPerformed

    private void jTextFieldFilenameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFilenameFocusGained
        toggleActions(false);
    }//GEN-LAST:event_jTextFieldFilenameFocusGained

    private void jTextFieldFilenameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldFilenameFocusLost
        toggleActions(true);
    }//GEN-LAST:event_jTextFieldFilenameFocusLost

    private void jTextFieldFilenameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilenameKeyTyped
        updateDestinationLabel();
    }//GEN-LAST:event_jTextFieldFilenameKeyTyped

    private void jTextFieldFilenameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFilenameKeyReleased
        updateDestinationLabel();
    }//GEN-LAST:event_jTextFieldFilenameKeyReleased

    private void jSplitPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSplitPane1MouseClicked
        saveSettings();
    }//GEN-LAST:event_jSplitPane1MouseClicked

    private void jCheckBoxCopyOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxCopyOnlyActionPerformed
        if (jCheckBoxCopyOnly.isSelected()) {
            jButtonMove.setText("Copy");
        } else {
            jButtonMove.setText("Move");
        }
    }//GEN-LAST:event_jCheckBoxCopyOnlyActionPerformed

    private void jButtonBrowseDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBrowseDirActionPerformed
        selectDirName();
    }//GEN-LAST:event_jButtonBrowseDirActionPerformed

    private void jComboBoxDirNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDirNameActionPerformed
        if (!initializing && !processingComboBox) {
            updateDestinationLabel();
            savePaths(dirNamesList, dirNamesFileName, jComboBoxDirName);
        }
    }//GEN-LAST:event_jComboBoxDirNameActionPerformed

    private void jComboBoxDirNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxDirNameKeyTyped
        updateDestinationLabel();
        saveSettings();
    }//GEN-LAST:event_jComboBoxDirNameKeyTyped

    private void jComboBoxDirNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBoxDirNameKeyReleased
        updateDestinationLabel();
        saveSettings();
    }//GEN-LAST:event_jComboBoxDirNameKeyReleased

    private void jComboBoxDirNameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxDirNameItemStateChanged
        String dirName = (String) jComboBoxDirName.getSelectedItem();
        if (!initializing && !processingComboBox && dirName != null) {
            //Get current selection, could have been typed in so need to update the dir name
                //list
            updateDirNameList(Paths.get(dirName));
            updateDestinationLabel();
        }
    }//GEN-LAST:event_jComboBoxDirNameItemStateChanged

    private void jButtonCustomizeActionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCustomizeActionsActionPerformed
        if (customActionsDialog == null) {
            customActionsDialog = new CustomActionsDialog(this, true);
        }
        customActionsDialog.setVisible(true);
        initCustomActions();
    }//GEN-LAST:event_jButtonCustomizeActionsActionPerformed

    private void jLabelNextMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNextMouseEntered
        jLabelNext.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelNextMouseEntered

    private void jLabelNextMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNextMouseExited
        jLabelNext.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabelNextMouseExited

    private void jLabelPreviousMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPreviousMouseEntered
        jLabelPrevious.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabelPreviousMouseEntered

    private void jLabelPreviousMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPreviousMouseExited
        jLabelPrevious.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jLabelPreviousMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImageSorterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImageSorterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImageSorterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImageSorterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initializing = true;
                imageSorterFrame = new ImageSorterFrame();
                imageSorterFrame.setVisible(true);
                initializing = false;
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private imageSorter.ImageLabel imageLabel;
    private javax.swing.JButton jButtonBrowseDeleteTo;
    private javax.swing.JButton jButtonBrowseDir;
    private javax.swing.JButton jButtonBrowseMoveTo;
    private javax.swing.JButton jButtonBrowseSource;
    private javax.swing.JButton jButtonCustomizeActions;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonMove;
    private javax.swing.JCheckBox jCheckBoxAutoCreateDirs;
    private javax.swing.JCheckBox jCheckBoxCopyOnly;
    private javax.swing.JComboBox<String> jComboBoxDeleteToDestination;
    private javax.swing.JComboBox<String> jComboBoxDirName;
    private javax.swing.JComboBox<String> jComboBoxMoveToDestination;
    private javax.swing.JComboBox<String> jComboBoxSource;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelDestination;
    private javax.swing.JLabel jLabelFilenameExtension;
    private javax.swing.JLabel jLabelMonth;
    private javax.swing.JLabel jLabelNext;
    private javax.swing.JLabel jLabelPrevious;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelXofY;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemRenameFile;
    private javax.swing.JMenuItem jMenuItemUndo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelCustomActions;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSliderBrowsePictures;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextFieldFilename;
    // End of variables declaration//GEN-END:variables

    private static ImageSorterFrame imageSorterFrame;
    private final String homeDir = System.getProperty("user.home");
    private final String appName = "ImageSorter";
    private List<Path> selectSourceList = new ArrayList<>(); 
    private final String sourceFileName = "imageSorterSourcePaths.txt";
    private List<Path> moveToList = new ArrayList<>(); 
    private final String moveToFileName = "imageSorterMoveToPaths.txt";
    private List<Path> deleteToList = new ArrayList<>();
    private final String deleteToFileName = "imageSorterDeleteToPaths.txt";
    private List<Path> dirNamesList = new ArrayList<>();
    private final String dirNamesFileName = "imageSorterDirNames.txt";
    private final String toolSettingsFileName = "imageSorterSettings.txt";
    private final static String CREATE_DATE_DIR = "Create Year and Month Directory";
    private final static String SUB_DIR_TEXT = "Sub directory text to use with date directory";
    private final static String HIDE_TOP_PART = "Collapse the top componnet";
    private static boolean initializing = false;
    private static boolean processingComboBox = false;
    private ArrayList<Path> filesList = new ArrayList<>();
    private int fileIndex;
    private Color defaultFG_Color;
    private static final String NEW_LINE = System.lineSeparator();
    private Path currentImageFilePath = null;
    private MouseListener imageMouseListener = null;
    private ImageSorterFrame thisObject = null;
    private String imageExtensions = "jpgjpeggifpng";
    private String videoExtensions = "mp4mov";
    private static final String PLAY_VIDEO_IMAGE_LOCATION = "ImageSorterPlayVideo.jpg"; //"playVideo.jpg"; //ImageSorterPlayVideo.jpg";
    private final static int MAX_SOURCE_ITEMS = 10;
    private final static int MAX_DEST_ITEMS = 10;
    private final static int MAX_DELETE_ITEMS = 10;
    private final static int MAX_DIR_NAME_ITEMS = 20;
    private CustomActionsDialog customActionsDialog = null;
    private LocalDateTime sourceDirectoryTimeStamp = null;
    private Map<JButton, CustomAction> customButtonActionMap = new TreeMap<>();
        
    private enum FileMoveType {
        MOVE("Move", "Moving"),
        COPY("Copy", "Copying"),
        DELETE("Delete", "Deleting"),
        COPY_CUSTOM("Copy Custom", "Copying"),
        ;
        
        private String description;
        private String actionDescription;

        private FileMoveType(String description, String actionDescription) {
            this.description = description;
            this.actionDescription = actionDescription;
        }
        
        
    }
    //File - Exit
    //Action - Undo
    //Version 0.2 Feb 3rd 2017: Fixed an error of 'null' with the destination path that can occur
    //                          Allow the custom dir to be used when not creating year/month in path
    //                          Check for the destination file.  Prompt to continue if it exists.
    //Version 0.3 Feb xx 2017: Change the splash screen...
    //Version 1.0 Feb 21 2017: Include mp4 and mov files.  Allow images and videos to be opened in the 
    //                         OS native tool for viewing/playing
    //Version 2.0 Oct 14 2017: Change the 'Move' button to 'Copy' if the copy checkbox is selected
    //                         When deleting, delete the source file even if the 'copy' checkbox is selected
    //                         Save up to 20 previously selected Dir Name values, while allowing a type-in vlaue
    //                         When looking for images, make the extension check case insensitive
    //                         Add tooltips to provide additional descriptions
    //                         Add the option to create customized additional locations to copy files to
    //Version 2.1 Dec 30 2017: When adding custom actions, auto fill in the name of the button when selecting a new directory
    //                         Add tooltips for the buttons in the custom actions dialog
    //                         The play video image isn't showing.
    //                         Neither is the splashscreen.
    //                         Unable to overwrite (in deleted location)
    //                         Allow the custom locations to be scrollable
    //                         When selecting a new custom location, default to the last selected location
    //                         Allow scrollbars for the list of custom buttons
    //                         Show the wait cursor when performing an action
    //                         Correct issues with the custom dir name
    //Version 2.2 Jan 29 2018: Do not advance to the next image when clicking on a custom location button
    //                         Allow the order of the buttons to be modified/saved by dragging/dropping them
    //                         When modifying the custom buttons, do not auto-resize the window (pack)
    //Version 2.3 xxx xx 2018: Allow the option to use the date/time stamp of the file or of the file name, allowing
    //                              the format within the filename to be specified (i.e. yyyymmdd).
    
    private void initMyComponents() {
        jPanelCustomActions.setLayout(new BoxLayout(jPanelCustomActions, BoxLayout.PAGE_AXIS));
        thisObject = this;
        imageMouseListener = new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {
                    Desktop.getDesktop().open(currentImageFilePath.toFile());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(thisObject, "Unable to open file\n\n\t" + currentImageFilePath.getFileName().toString(), "Can't Open File", JOptionPane.ERROR_MESSAGE);
                }
            }

            @Override
            public void mousePressed(MouseEvent e) {}

            @Override
            public void mouseReleased(MouseEvent e) {}

            @Override
            public void mouseEntered(MouseEvent e) {
                imageLabel.setCursor(new Cursor(Cursor.HAND_CURSOR));
            }

            @Override
            public void mouseExited(MouseEvent e) {}
        };
        
        imageLabel.addMouseListener(imageMouseListener);
        
        defaultFG_Color = jLabelDestination.getForeground();
        jCheckBoxAutoCreateDirs.setSelected(true);
        setTitle("Image Sorter Version 2.2 (Jan 2018)");

        jComboBoxSource.setMaximumRowCount(MAX_SOURCE_ITEMS);
        int selectedIndex = getPaths(sourceFileName, selectSourceList, MAX_SOURCE_ITEMS);
        populateComboBox(selectSourceList, jComboBoxSource, selectedIndex);

        jComboBoxMoveToDestination.setMaximumRowCount(MAX_DEST_ITEMS);
        selectedIndex = getPaths(moveToFileName, moveToList, MAX_DEST_ITEMS);
        populateComboBox(moveToList, jComboBoxMoveToDestination, selectedIndex);

        jComboBoxDeleteToDestination.setMaximumRowCount(MAX_DELETE_ITEMS);
        selectedIndex = getPaths(deleteToFileName, deleteToList, MAX_DELETE_ITEMS);
        populateComboBox(deleteToList, jComboBoxDeleteToDestination, selectedIndex);
       
        jComboBoxDirName.setMaximumRowCount(MAX_DIR_NAME_ITEMS);
        selectedIndex = getPaths(dirNamesFileName, dirNamesList, MAX_DIR_NAME_ITEMS);
        populateComboBox(dirNamesList, jComboBoxDirName, selectedIndex);
        
        getSettings();
        
        getSourceFiles(false);
        
        ArrayList<Integer> rightActionList = new ArrayList<>();
        rightActionList.add(KeyEvent.VK_PERIOD);
        rightActionList.add(KeyEvent.VK_RIGHT);
        
        ArrayList<Integer> leftActionList = new ArrayList<>();
        leftActionList.add(KeyEvent.VK_COMMA);
        leftActionList.add(KeyEvent.VK_LEFT);

        ArrayList<Integer> moveActionList = new ArrayList<>();
        moveActionList.add(KeyEvent.VK_M);

        ArrayList<Integer> deleteActionList = new ArrayList<>();
        deleteActionList.add(KeyEvent.VK_BACK_SPACE);
        deleteActionList.add(KeyEvent.VK_DELETE);

        ArrayList<Integer> undoActionList = new ArrayList<>();
        undoActionList.add(KeyEvent.VK_Z);

        ArrayList<Integer> renameFileActionList = new ArrayList<>();
        renameFileActionList.add(KeyEvent.VK_N);

        JPanel content = ((JPanel) this.getContentPane());
        
        //Determines correct key (Ctrl for Windows, Cmd for Mac)
        int ctrlOrMeta = Toolkit.getDefaultToolkit().getMenuShortcutKeyMask();
        
        jMenuItemUndo.setAccelerator(getKeyStroke(KeyEvent.VK_Z, ctrlOrMeta));
        jMenuItemRenameFile.setAccelerator(getKeyStroke(KeyEvent.VK_N, ctrlOrMeta));
        
        
        InputMap inputMap = content.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        //InputMap inputMapWhenAncestor = content.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        
        for (int i = 0; i < rightActionList.size(); i++) {
            inputMap.put(KeyStroke.getKeyStroke(rightActionList.get(i), 0), "nextImage" + i);
            content.getActionMap().put("nextImage" + i, RightAction);
        }
        
        for (int i = 0; i < leftActionList.size(); i++) {
            inputMap.put(KeyStroke.getKeyStroke(leftActionList.get(i), 0), "previousImage" + i);
            content.getActionMap().put("previousImage" + i, LeftAction);
        }
        
        for (int i = 0; i < moveActionList.size(); i++) {
            inputMap.put(KeyStroke.getKeyStroke(moveActionList.get(i), ctrlOrMeta), "moveImageCmd" + i);
            content.getActionMap().put("moveImageCmd" + i, MoveAction);
//            inputMap.put(KeyStroke.getKeyStroke(moveActionList.get(i), InputEvent.META_DOWN_MASK), "moveImageCmd" + i);
//            content.getActionMap().put("moveImageCmd" + i, MoveAction);
        }
        
        for (int i = 0; i < deleteActionList.size(); i++) {
            inputMap.put(KeyStroke.getKeyStroke(deleteActionList.get(i), 0), "deleteImage" + i);
            content.getActionMap().put("deleteImage" + i, DeleteAction);
        }
        
        for (int i = 0; i < undoActionList.size(); i++) {
            inputMap.put(KeyStroke.getKeyStroke(undoActionList.get(i), InputEvent.META_DOWN_MASK), "undoDelete" + i);
            content.getActionMap().put("undoDelete" + i, UndoDeleteAction);
        }
        
        for (int i = 0; i < renameFileActionList.size(); i++) {
            inputMap.put(KeyStroke.getKeyStroke(renameFileActionList.get(i), InputEvent.META_DOWN_MASK), "renameFile" + i);
            content.getActionMap().put("renameFile" + i, RenameFileAction);
        }
        
        inputMap = jTextFieldFilename.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        ArrayList<Integer> allActionsList = new ArrayList<>();
        allActionsList.addAll(rightActionList);
        allActionsList.addAll(leftActionList);
        allActionsList.addAll(deleteActionList);
        allActionsList.addAll(undoActionList);
        allActionsList.addAll(renameFileActionList);
        
//        for (int i = 0; i < allActionsList.size(); i++) {
//            inputMap.put(KeyStroke.getKeyStroke(allActionsList.get(i), 0), "doNothing" + i);
//            jTextFieldFilename.getActionMap().put("doNothing" + i, NothingAction);
//        }
        
        
        jSliderBrowsePictures.addChangeListener(sliderChange);
        
        initCustomActions();
        
        showStatusLabel.start();
    }

    public String getHomeDir() {
        return homeDir;
    }

    public String getAppName() {
        return appName;
    }
    
    private void initCustomActions() {
        //Get all the custom action objects
        if (customActionsDialog == null) {
            customActionsDialog = new CustomActionsDialog(this, true);
        }
        List<CustomActionsDialog.CustomAction> customActions = customActionsDialog.getCustomActions();
        GridBagConstraints gbc;
        
        int rowCount = 0;
        
        jPanelCustomActions.removeAll();
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = rowCount ++;
        gbc.fill = GridBagConstraints.HORIZONTAL;

        jPanelCustomActions.add(jButtonCustomizeActions, gbc);
        
        Box.Filler gap = new Box.Filler(new Dimension(10, 15), new Dimension(10, 15), new Dimension(10, 15));
        gbc.gridy = rowCount ++;
        jPanelCustomActions.add(gap, gbc);
        
        //gbc.insets = new Insets(10, 10, 10, 10);
        customButtonActionMap = new HashMap<>();
        
        for (int i = 0; i < customActions.size(); i++) {
            CustomAction customAction = customActions.get(i);
            if (!customAction.enabled) continue;
            JButton customSaveButton = new JButton(customAction.toString());
            //customSaveButton.setPreferredSize(new Dimension(0, 35));
            customSaveButton.setToolTipText("Copy To " + customAction.directory.toString());
            customSaveButton.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    moveImage(getDestination(customAction.directory.toString(), FileMoveType.COPY_CUSTOM), FileMoveType.COPY_CUSTOM);
                }
            });
            DragListener drag = new DragListener();
            customSaveButton.addMouseListener( drag );
            customSaveButton.addMouseMotionListener( drag );
            
            gbc.gridy = i + rowCount;
            jPanelCustomActions.add(customSaveButton, gbc);
            customButtonActionMap.put(customSaveButton, customAction);
        }
        
        jPanelCustomActions.revalidate();
        jPanelCustomActions.repaint();
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
        if (imageSorterFrame == null) {
            pack();
        } else {
            //Rectangle dimensions = imageSorterFrame.getBounds();
            //imageSorterFrame.pack();
            //imageSorterFrame.setBounds(dimensions);
        }
    }
    
    private int alpha = 255;
    private int alphaCounter = 0;
    private int increment = -5;
    private boolean showStatus = false;
    private boolean hideStatus = false;
    
    Timer showStatusLabel = new Timer(10, new ActionListener() {
      public void actionPerformed(ActionEvent e) {
          if (showStatus) {
              alpha = 0;
              alphaCounter = 0;
              increment = 5;
              showStatus = false;
          }
        alphaCounter += increment;
        if (alphaCounter > 255) {
            alpha = 255;
            if (alphaCounter > 400) {
                increment = -5;
                //alphaCounter = 255;
            }
        } else if (alphaCounter < 0) {
            alpha = 0;
            increment = 0;
        } else {
            alpha = alphaCounter;
        }
        //if (alpha >= 255) {
        //  alpha = 255;
        //  increment = -increment;
        //}
        //if (alpha <= 0) {
        //  alpha = 0;
        //  increment = -increment;
        //}
        jLabelStatus.setForeground(new Color(0, 102, 0, alpha));
      }
    });
    
    Action RightAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            jLabelNextMouseClicked(null);
        }
    };

    Action LeftAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            jLabelPreviousMouseClicked(null);
        }
    };

    Action NothingAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            //Do Nothing
        }
    };
    
    Action MoveAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            jButtonMoveActionPerformed(e);
        }
    };

    Action DeleteAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            jButtonDeleteActionPerformed(e);
        }
    };

    Action UndoDeleteAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            jMenuItemUndoActionPerformed(e);
        }
    };
    
    Action RenameFileAction = new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            selectFileNameField();
        }
    };
    
    private void toggleActions(boolean enable) {
        RightAction.setEnabled(enable);
        LeftAction.setEnabled(enable);
        NothingAction.setEnabled(enable);
        MoveAction.setEnabled(enable);
        DeleteAction.setEnabled(enable);
        UndoDeleteAction.setEnabled(enable);
        RenameFileAction.setEnabled(enable);
    }
    
    ChangeListener sliderChange = new ChangeListener() {
        @Override
        public void stateChanged(ChangeEvent e) {
            fileIndex = jSliderBrowsePictures.getValue() - 1;
            setImage();
        }
    };

    @Override
    public void dispose() {
        int response = JOptionPane.showConfirmDialog(this, "Are you sure you want to exit?", "Exiting Image Sorter", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);
        if (response == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }

    @Override
    protected void processKeyEvent(KeyEvent e) {
        System.out.println("Key Event:" + e.paramString() + "; key code:" + e.getKeyCode());
        if (e.getKeyCode() == KeyEvent.VK_RIGHT) {
            jLabelNextMouseClicked(null);
        }
        super.processKeyEvent(e); //To change body of generated methods, choose Tools | Templates.
    }

    private void selectSource() {
        selectDir(jComboBoxSource, selectSourceList);
        savePaths(selectSourceList, sourceFileName, null);
        getSourceFiles(false);
    }
    
    private FilenameFilter filter = new FilenameFilter() {
        @Override
        public boolean accept(File dir, String name) {
            String ext = FileUtilities.getExtension(new File(name));
            if (ext == null) return false;
            return (imageExtensions + videoExtensions).contains(ext);
        }
    };

    /**
     * Refreshes the list of files, but only if there have been changes to the source directory
     */
    private void getSourceFiles(boolean forceReload) {
        if (jComboBoxSource.getSelectedItem() == null) return;
        //Now get the files...
        if (forceReload || isSourceDirectoryUpdated()) {
            filesList = FileUtilities.getDirFiles(Paths.get((String) jComboBoxSource.getSelectedItem()), false, filter);
            if (filesList.size() > 0) {
                fileIndex = 0;
                setImage();
                resetSlider(1);
            } else {
                setNoImage();
            }
        }        
    }
    
    public boolean isSourceDirectoryUpdated() {
        if (jComboBoxSource.getSelectedItem() == null) return false;
        boolean sourceUpdated = false;
        File sourceDir = Paths.get((String) jComboBoxSource.getSelectedItem()).toFile();
        if (sourceDir.isDirectory()) {
            LocalDateTime sourceDirTimeStamp = LocalDateTime.ofInstant(Instant.ofEpochMilli(sourceDir.lastModified()), ZoneId.systemDefault());
            if (sourceDirectoryTimeStamp == null) {
                sourceUpdated = true;
            } else {
                sourceUpdated = sourceDirTimeStamp.isAfter(sourceDirectoryTimeStamp);
            }
            sourceDirectoryTimeStamp = sourceDirTimeStamp;
        }
        return sourceUpdated;
    }
    
    private void resetSlider(int value) {
        jSliderBrowsePictures.setMaximum(filesList.size());
        jSliderBrowsePictures.setMinimum(1);
        jSliderBrowsePictures.setValue(value);
    }
    
    private void getNextImage() {
        fileIndex ++;
        if (fileIndex < 0) fileIndex = 1;
        if (fileIndex > filesList.size() - 1) return;
        setImage();
    }
    
    private void getPreviousImage() {
        fileIndex --;
        if (fileIndex > filesList.size() - 1) fileIndex = filesList.size() - 2;
        if (fileIndex < 0) return;
        setImage();
    }
    
    private void setImage() {
        jLabelXofY.setText((fileIndex + 1) + " of " + filesList.size());
        if (fileIndex < 0) {
            setNoImage();
            return;
        }
        Path imageFile = filesList.get(fileIndex);
        currentImageFilePath = imageFile;
        if (isImage(imageFile)) {
            ImageIcon imageIcon = new ImageIcon(imageFile.toString());
            imageLabel.setImage(imageIcon.getImage());
            imageLabel.setToolTipText("Open image in image viewer");
        } else {
            try {
                //DT:  The following uses jcodec libaries (2) that grabs a frame from the video.  It's pretty slow, though.
                    //Picture picture = FrameGrab.getFrameFromFile(imageFile.toFile(), 1);
                    //BufferedImage bufferedImage = AWTUtil.toBufferedImage(picture);
                    //ImageIcon imageIcon = new ImageIcon(bufferedImage);
                //DT:  Long term, FFMpeg may be the best tool to use -- command line option
                ImageIcon imageIcon = new ImageIcon(getClass().getResource("/images/" + PLAY_VIDEO_IMAGE_LOCATION));
                imageLabel.setImage(imageIcon.getImage());
                imageLabel.setToolTipText("Open/play video in player");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, "Problem with video\n\n\t" + imageFile.getFileName().toString(), "Problem Showing Video Image", JOptionPane.ERROR_MESSAGE);
            }
        }
        jTextFieldFilename.setText(FileUtilities.getPrefix(imageFile.getFileName().toFile()));
        jLabelFilenameExtension.setText("." + FileUtilities.getExtension(imageFile.getFileName().toFile()));
        
        long lastModified = imageFile.toFile().lastModified();
        LocalDateTime fileDateTime = LocalDateTime.ofInstant(Instant.ofEpochMilli(lastModified), ZoneId.systemDefault());
        String year = String.valueOf(fileDateTime.getYear());
        String month = fileDateTime.getMonth().getDisplayName(TextStyle.FULL, Locale.getDefault());
        jLabelYear.setText(year);
        jLabelMonth.setText(month);
        resetSlider(fileIndex + 1);
        updateDestinationLabel();
    }
    
    private boolean isImage(Path imageFile) {
        Path pathFile = imageFile.getFileName();
        String ext = pathFile.toString().substring(pathFile.toString().lastIndexOf(".") + 1).toLowerCase();
        return imageExtensions.contains(ext);
    }
    
    private void setNoImage() {
        jLabelXofY.setText("No images in this directory");
        imageLabel.setImage(null);
        jTextFieldFilename.setText(null);
        jLabelFilenameExtension.setText(null);
        jLabelYear.setText(null);
        jLabelMonth.setText(null);
        jLabelDestination.setText(null);
        String dirToDelete = (String) jComboBoxSource.getSelectedItem();
        Path deletePath = Paths.get(dirToDelete);
        String[] fileList = deletePath.toFile().list();
        if (fileList == null) {
            JOptionPane.showMessageDialog(this, "Cannot find\n\n\t" + dirToDelete, "Directory Not Found", JOptionPane.ERROR_MESSAGE);
        } else {
            boolean isEmpty = fileList.length < 1;
            if (isEmpty) {
                int response = JOptionPane.showConfirmDialog(this, "The directory \n\n\t" + dirToDelete + "\n\nis empty.  Do you want to delete it?", "Empty Directory",
                                                            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                    boolean deleteSuccessful = FileUtilities.deleteDirectory(Paths.get(dirToDelete).toFile());
                    if (deleteSuccessful) {
                        //Remove it from the remembered list of dirs
                        for (Iterator<Path> iterator = selectSourceList.iterator(); iterator.hasNext();) {
                            String pathStr = iterator.next().toString();
                            if (pathStr.equals(dirToDelete)) {
                                iterator.remove();
                            }
                        }
                        //Need to save and rebuild
                        if (jComboBoxSource.getSelectedIndex() > -1) {
                            jComboBoxSource.remove(jComboBoxSource.getSelectedIndex());
                        }            
                        savePaths(selectSourceList, sourceFileName, jComboBoxSource);
                        int selectedIndex = getPaths(sourceFileName, selectSourceList, MAX_SOURCE_ITEMS);
                        populateComboBox(selectSourceList, jComboBoxSource, selectedIndex);
                        getSourceFiles(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Unable to delete the directory.  Not sure why, though.", "Directory Could Not Be Deleted", JOptionPane.WARNING_MESSAGE);
                    }
                }
            } else {
                //JOptionPane.showMessageDialog(this, "The directory\n\n\t" + dirToDelete + "\n\nis not empty, but there are no images.", "No Images Found", JOptionPane.WARNING_MESSAGE);
            }
        }
    }
    
    private void selectMoveTo() {
        selectDir(jComboBoxMoveToDestination, moveToList);
        savePaths(moveToList, moveToFileName, jComboBoxMoveToDestination);
    }
    
    private void selectDeleteTo() {
        selectDir(jComboBoxDeleteToDestination, deleteToList);
        savePaths(deleteToList, deleteToFileName, jComboBoxDeleteToDestination);
    }
    
    private void selectDirName() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        Path currPath = getDestination((String) jComboBoxMoveToDestination.getSelectedItem(), FileMoveType.MOVE);
        if (currPath != null) {
            chooser.setCurrentDirectory(currPath.getParent().getParent().toFile());
        }
        int returnValue = chooser.showDialog(this, "Select Dir");
        switch(returnValue) {
            case JFileChooser.CANCEL_OPTION:
                return;
            case JFileChooser.ERROR_OPTION:
                JOptionPane.showMessageDialog(this, "There was an error", "Error Selecting Directory", JOptionPane.OK_OPTION);
                return;
            case JFileChooser.APPROVE_OPTION:
                break;
        }
        File dirItem = chooser.getSelectedFile();
        Path newPath = dirItem.toPath();
        
        if (newPath != null) {
            Path dirName = newPath.getFileName();
            //If it starts with a 2 digit number, remove first 3 chars
            if (dirName.toString().matches("^[0-9]{2}.*")) {
                dirName = Paths.get(dirName.toString().substring(3));
            }
            updateDirNameList(dirName);
            updateDestinationLabel();
        }
    }
    
    private void selectFileNameField() {
        jTextFieldFilename.requestFocus();
        jTextFieldFilename.selectAll();
    }

    private void selectDir(JComboBox<String> comboBox, List<Path> comboList) {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        String selectedDir = (String) comboBox.getSelectedItem();
        Path currPath = null;
        if (selectedDir != null) {
            currPath = Paths.get(selectedDir);
        }
        if (currPath != null) {
            chooser.setCurrentDirectory(currPath.toFile());
        }
        int returnValue = chooser.showDialog(this, "Select Dir");
        switch(returnValue) {
            case JFileChooser.CANCEL_OPTION:
                return;
            case JFileChooser.ERROR_OPTION:
                JOptionPane.showMessageDialog(this, "There was an error", "Error Selecting Directory", JOptionPane.OK_OPTION);
                return;
            case JFileChooser.APPROVE_OPTION:
                break;
        }
        File dirItem = chooser.getSelectedFile();
        Path newPath = dirItem.toPath();
        
        if (newPath != null) {
            //Add it to the list and refresh the combo box
            comboList.add(0, newPath);
            populateComboBox(comboList, comboBox, 0);
        }
    }
    
    private void updateDirNameList(Path dirName) {
        //Add it to the list and refresh the combo box if it doesn't exist
        boolean alreadyExists = false;
        for (int i = 0; i < dirNamesList.size(); i++) {
            if (dirNamesList.get(i).toString().equals(dirName.toString())) {
                processingComboBox = true;
                jComboBoxDirName.setSelectedIndex(i);
                processingComboBox = false;
                alreadyExists = true;
                break;
            }
        }
        if (!alreadyExists) {
            dirNamesList.add(0, dirName);
            processingComboBox = true;
            jComboBoxDirName.setSelectedIndex(0);
            processingComboBox = false;
            populateComboBox(dirNamesList, jComboBoxDirName, 0);
        }
        savePaths(dirNamesList, dirNamesFileName, jComboBoxDirName);        
    }
    
    private int getPaths(String fileName, List<Path> pathsList, int maxNumItems) {
        int selectedIndex = -10;
        try {
            ArrayList<String> directoriesList = FileUtilities.readLinesFromFile(Paths.get(homeDir, appName, fileName));
            pathsList.clear();
            List<String> prefsList = new ArrayList<>();
            for (int i = 0; i < Math.min(maxNumItems, directoriesList.size()); i ++) {
                String pref = directoriesList.get(i);
                if (prefsList.contains(pref)) continue;
                if (selectedIndex == -10) {
                    try {
                        selectedIndex = Integer.parseInt(pref);
                        continue;
                    } catch (Exception ex1) {
                        //First line wasn't the index
                    }
                }
                pathsList.add(Paths.get(pref));
                prefsList.add(pref);
            }
        } catch (Exception ex2) {
            ex2.printStackTrace();
        }
        return selectedIndex;
    }
    
    private void populateComboBox(List<Path> pathList, JComboBox<String> comboBox, int selectedIndex) {
        processingComboBox = true;        
        comboBox.removeAllItems();
        if (pathList.size() > (comboBox.getMaximumRowCount() + 1)) {
            pathList = pathList.subList(0, comboBox.getMaximumRowCount());
        }
        for (Path path : pathList) {
            comboBox.addItem(path.toString());
        }
        if (selectedIndex > -1 && selectedIndex < comboBox.getModel().getSize()) {
            comboBox.setSelectedIndex(selectedIndex);
        }
        processingComboBox = false;
    }
    
    private void updateDestinationLabel() {
        Path destinationPath = getDestination((String) jComboBoxMoveToDestination.getSelectedItem(), FileMoveType.MOVE);
        if (destinationPath != null) {
            if (destinationPath.toFile().exists()) {
                jLabelDestination.setForeground(Color.red);
                jLabelDestination.setToolTipText("A file with the same name already exists at the destination");
            } else {
                jLabelDestination.setForeground(defaultFG_Color);
                jLabelDestination.setToolTipText("Full path and name of the destination");
            }
            jLabelDestination.setText(destinationPath.toString());
        }
    }
    
    private Path getDestination(String destination, FileMoveType moveType) {
        if ((fileIndex + 1 > filesList.size())
                || destination == null) return null;
        if (fileIndex < 0) {
            if (filesList.size() > 0) {
                fileIndex = 0;
            } else {
                return null;
            }
        }
        Path sourceFile = filesList.get(fileIndex);
        Path moveToPathAndFile = Paths.get(destination);
        if (jCheckBoxAutoCreateDirs.isSelected()
                && moveType != null
                && (moveType == FileMoveType.MOVE
                    || moveType == FileMoveType.COPY)) {
            long lastModified = sourceFile.toFile().lastModified();
            LocalDateTime fileDateTime = LocalDateTime.ofInstant(Instant.ofEpochMilli(lastModified), ZoneId.systemDefault());
            String year = String.valueOf(fileDateTime.getYear());
            String month = String.valueOf(fileDateTime.getMonthValue());
            if (month.length() < 2) {
                month = "0" + month;
            }
            if (jComboBoxDirName.getModel() != null
                    && jComboBoxDirName.getModel().getSize() > 0
                    && ((String) jComboBoxDirName.getSelectedItem() != null)
                    && !((String) jComboBoxDirName.getSelectedItem()).trim().isEmpty()) {
                month = month + "_" + ((String) jComboBoxDirName.getSelectedItem()).trim();
            }
            moveToPathAndFile = Paths.get(destination, year, month);
        } else if (moveType != null
                    && (moveType == FileMoveType.MOVE
                        || moveType == FileMoveType.COPY)) {
            //check for a custom dir name
            if (jComboBoxDirName.getModel() != null
                    && jComboBoxDirName.getModel().getSize() > 0
                    && ((String) jComboBoxDirName.getSelectedItem() != null)
                    && !((String) jComboBoxDirName.getSelectedItem()).trim().isEmpty()) {
                moveToPathAndFile = Paths.get(destination, ((String) jComboBoxDirName.getSelectedItem()).trim());
            }
        }
        String fileExtension = jLabelFilenameExtension.getText();
        String fileName = jTextFieldFilename.getText();
        fileName = fileName + fileExtension;
        moveToPathAndFile = moveToPathAndFile.resolve(fileName);
        return moveToPathAndFile;
        //jLabelDestination.setText(moveToPathAndFile.toString());
    }
    
    private void savePaths(List<Path> pathList, String fileName, JComboBox<String> comboBox) {
        if (comboBox == null || comboBox.getModel() == null) return;
        StringBuffer stringToWrite = new StringBuffer("");
        int selectedIndex = 0;
        if (comboBox.getModel().getSize() > 0) {
            selectedIndex = comboBox.getSelectedIndex();
        }
        stringToWrite.append(String.valueOf(selectedIndex)).append("\n");
        for (Path source : pathList) {
            stringToWrite.append(source.toString()).append("\n");
        }        
        Path fileDest = Paths.get(homeDir, appName, fileName);
        try {
            FileUtilities.writeStringToFile(fileDest, stringToWrite, false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Problem saving paths:  " + ex.getMessage(), 
                    "Issue Saving Paths", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    private void getSettings() {
        try {
            ArrayList<String> settingsList = FileUtilities.readLinesFromFile(Paths.get(homeDir, appName, toolSettingsFileName));
            String temp;
            for (String pref : settingsList) {
                String[] setting = pref.split(",");
                if (setting.length < 2) continue;
                temp = setting[1];
                if (null != setting[0]) switch (setting[0]) {
                    case CREATE_DATE_DIR:
                        jCheckBoxAutoCreateDirs.setSelected(Boolean.valueOf((String) temp));
                        break;
                    //case SUB_DIR_TEXT:
                    //    jTextFieldDirName.setText(setting[1]);
                    //    break;
                    case HIDE_TOP_PART:
                        jSplitPane1.setDividerLocation(Integer.parseInt(setting[1]));
                        break;
                    default:
                        break;
                }
            }
        } catch (Exception ex) {
            
        }
    }
    
    private void saveSettings() {
        StringBuffer stringToWrite = new StringBuffer("");
        stringToWrite.append(CREATE_DATE_DIR).append(",").append(jCheckBoxAutoCreateDirs.isSelected()).append("\n");
        //stringToWrite.append(SUB_DIR_TEXT).append(",").append(jTextFieldDirName.getText()).append("\n");
        stringToWrite.append(HIDE_TOP_PART).append(",").append(jSplitPane1.getDividerLocation()).append("\n");
        Path fileDest = Paths.get(homeDir, appName, toolSettingsFileName);
        try {
            FileUtilities.writeStringToFile(fileDest, stringToWrite, false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Problem saving settings:  " + ex.getMessage(), 
                    "Issue Saving Settings", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    /*-----------------------------------------*/
    
    private void moveImage(Path destination, FileMoveType moveType) {
        if (destination == null) return;
        boolean sourceDirUpdatedBeforeModification = isSourceDirectoryUpdated();
        if (sourceDirUpdatedBeforeModification) {
            JOptionPane.showMessageDialog(this, "The source directory has been modified.  The action will be cancelled and"
                    + " the list refreshed.", 
                    "Source Directory Externally Modified", JOptionPane.WARNING_MESSAGE);
            int currentFileIndex = fileIndex;
            getSourceFiles(true);
            //Try to set the current image to the previous file index
            fileIndex = currentFileIndex;
            setImage();
            this.setCursor(Cursor.getDefaultCursor());
            return;
        }
        this.setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        //Get the file source
        Path sourceFile = filesList.get(fileIndex);
        int numFilesBefore = filesList.size();
        try {
            if (moveType != FileMoveType.DELETE
                    && destination.toFile().exists()) {
                if (!FileUtilities.isDestFileSame(sourceFile.toFile(), destination.toFile())) {
                    Image bi = ImageIO.read(destination.toFile());
                    ImageIcon icon = new ImageIcon(bi.getScaledInstance(200, 200, Image.SCALE_SMOOTH));

                    //Check to see if they want ot overwrite it anyway...
                    int response = JOptionPane.showConfirmDialog(this, "A file with the same name already exists."
                            + NEW_LINE + "Are you sure"
                            + " you want to overwrite the destination file??"
                            + NEW_LINE + "Overwriting cannot be undone...",
                            "File Already Exists", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, icon);
                    if (response != JOptionPane.YES_OPTION) {
                        this.setCursor(Cursor.getDefaultCursor());
                        return;
                    }
                }
            }
            boolean success = FileUtilities.isDestFileSame(sourceFile.toFile(), destination.toFile());
            if (!success) {
                success = FileUtilities.copyFile(sourceFile, destination);
            }
            if (!success) throw new Exception("Could not copy the file over");
            boolean fileDeleted = false;
            if ((moveType == FileMoveType.DELETE)
                    || moveType == FileMoveType.MOVE) {
                //Verify the destination file is there before deleting
                if (destination.toFile().exists()) {
                    fileDeleted = Files.deleteIfExists(sourceFile);
                    if (!fileDeleted) {
                        throw new Exception("The file copy succeeded, but the source couldn't be deleted.");
                    }
                    //Reset the time stamp since a file was deleted from the directory... but only if the source dir wasn't
                        //already modified
                    if (!sourceDirUpdatedBeforeModification) {
                        sourceDirectoryTimeStamp = null;
                        isSourceDirectoryUpdated();
                    }
                } else {
                    throw new Exception("The media file didn't make it to it's destination... action cancelled, please try again.");
                }
            }
            if (fileDeleted) {
                filesList.remove(fileIndex);
            }
            int numFilesAfter = filesList.size();
            if ((moveType == FileMoveType.DELETE)
                    || moveType == FileMoveType.MOVE) {
                //The difference between the before and after should be only 1
                if (numFilesBefore - numFilesAfter != 1) {
                    throw new Exception("The number of files left after " + moveType.actionDescription.toLowerCase() 
                            + " should have been " + (numFilesBefore - 1) + " but it was " + numFilesAfter);
                }
                int originalIndex = fileIndex;
                getSourceFiles(false);
                if (numFilesAfter != filesList.size()) {
                    throw new Exception("The number of files after " + moveType.actionDescription.toLowerCase() 
                            + " was " + numFilesAfter + " but reading the source files again resulted in "
                            + filesList.size() + " files");
                }
                fileIndex = originalIndex;
            }
            if (fileIndex > filesList.size() - 1) {
                fileIndex = filesList.size() - 1;
            }
            fileActionsList.add(0, new FileAction(sourceFile, destination, moveType));
            if ((moveType == FileMoveType.COPY)
                    && filesList.size() > 0) {
                //Move the file index to the next image, or wrap around to the beginning if at the end
                fileIndex ++;
                if (fileIndex > filesList.size() - 1) {
                    fileIndex = 0;
                }
            }
            setImage();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Problem " + moveType.actionDescription.toLowerCase() + " file:  " + ex.getMessage(), 
                    "Issue " + moveType.actionDescription.toLowerCase() + " File", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
        jLabelStatus.setText(moveType.actionDescription + " Complete...");
        showStatus = true;
        this.setCursor(Cursor.getDefaultCursor());
    }

    private void undoLastAction() {
        if (fileActionsList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No action to undo", 
                    "No Undos Available", JOptionPane.WARNING_MESSAGE);
            return;
        }
        FileAction lastAction = fileActionsList.remove(0);
        try {
            boolean success = FileUtilities.copyFile(lastAction.getTo(), lastAction.getFrom());
            if (!success) throw new Exception("Are you sure the destination and source are different?");
            Files.delete(lastAction.getTo());
            int originalIndex = fileIndex;
            getSourceFiles(false);
            fileIndex = originalIndex;
            //Figure out which index was undeleted
            for (int i = 0; i < filesList.size(); i++) {
                if (lastAction.getFrom().compareTo(filesList.get(i)) == 0) {
                    fileIndex = i;
                    break;
                }
            }
            if (originalIndex > filesList.size() - 1) {
                fileIndex = filesList.size() - 1;
            }
            setImage();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Problem undoing last action for file '"
                    + lastAction.getTo().getFileName() + "':  " + ex.getMessage(), 
                    "Issue Undoing Action", JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }
    
    private ArrayList<FileAction> fileActionsList = new ArrayList<>();
    
    class FileAction {
        Path from;
        Path to;
        FileMoveType movementType;
        int indexLocation; //Where to put the picture back into the list??

        public FileAction(Path from, Path to, FileMoveType movementType) {
            this.from = from;
            this.to = to;
            this.movementType = movementType;
        }

        public Path getFrom() {
            return from;
        }

        public Path getTo() {
            return to;
        }

        public FileMoveType getMovementType() {
            return movementType;
        }
        
    }
    
    class DragListener extends MouseInputAdapter {
        Point location;
        MouseEvent pressed;
 
        public void mousePressed(MouseEvent me)
        {
            pressed = me;
        }

        public void mouseDragged(MouseEvent me)
        {
            Component component = me.getComponent();
            location = component.getLocation(location);
            int x = location.x - pressed.getX() + me.getX();
            int y = location.y - pressed.getY() + me.getY();
            component.setLocation(x, y);
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            super.mouseReleased(e); //To change body of generated methods, choose Tools | Templates.
            //Go through the buttons, re-arrange the custom actions according to where the button is
                //physically located
            List<CustomAction> customActionsListTemp = new ArrayList<>();
            List<CustomAction> customActions = customActionsDialog.getCustomActions();
            //customActions.clear();
            int index = 0;
            Map<JButton, CustomAction> tempCustomButtonMap = new TreeMap<>(new Comparator<JButton>() {
                @Override
                public int compare(JButton o1, JButton o2) {
                    if (o1.getY() > o2.getY()) {
                        return 1;
                    }
                    if (o1.getY() < o2.getY()) {
                        return -1;
                    }
                    return o1.getText().compareToIgnoreCase(o2.getText());
                }
            });
            for (Map.Entry<JButton, CustomAction> entry : customButtonActionMap.entrySet()) {
                JButton button = entry.getKey();
                CustomAction action = entry.getValue();
                tempCustomButtonMap.put(button, action);
            }

            for (Map.Entry<JButton, CustomAction> entry : tempCustomButtonMap.entrySet()) {
                JButton button = entry.getKey();
                CustomAction action = entry.getValue();
                for (Iterator<CustomAction> iterator = customActions.iterator(); iterator.hasNext();) {
                    CustomAction next = iterator.next();
                    if (next == action) {
                        iterator.remove();
                        break;
                    }
                }
                customActions.add(index, action);
                index ++;
            }
            customActionsDialog.saveSortedActions();
            initCustomActions();
        }        
        
    }

}
